export function _catchError(error, vnode) {
	console.log('报错了')
}
